export const AMIBOGCXC_Facturas_ES = {
        "AMIBOGCXCFacturaid" : "id",
        "AMIBOGCXCFacturaidError" : "id invalido", 
        "AMIBOGCXCFacturaFecha" : "Fecha",
        "AMIBOGCXCFacturaFechaError" : "Fecha invalido", 
        "ClienteAMIBOGCXCId" : "Razon Social",
        "ClienteAMIBOGCXCIdError" : "Razon Social invalido", 
        "ClienteAMIBOGCXCRazonSocial" : "Razon Social",
        "ClienteAMIBOGCXCRazonSocialError" : "Razon Social invalido", 
        "AMIBOGCXCFacturaFormaPago" : "Forma Pago",
        "_AMIBOGCXCFacturaFormaPago" : {
            "Contado" : "Contado",
            "Efectivo" : "Efectivo",
            "Cheque" : "Cheque",
            "Transferencia" : "Transferencia",
        },
        "AMIBOGCXCFacturaFormaPagoError" : "Forma Pago invalido", 
        "AMIBOGCXCFacturaSubTotal" : "Sub Total",
        "AMIBOGCXCFacturaSubTotalError" : "Sub Total invalido", 
        "AMIBOGCXCFacturaIva" : "Iva",
        "AMIBOGCXCFacturaIvaError" : "Iva invalido", 
        "AMIBOGCXCFacturaTotal" : "Total",
        "AMIBOGCXCFacturaTotalError" : "Total invalido", 
        "AMIBOGCXCFacturaDescuento" : "Descuento",
        "AMIBOGCXCFacturaDescuentoError" : "Descuento invalido", 
        "AMIBOGCXCFacturaObservaciones" : "Observaciones",
        "AMIBOGCXCFacturaObservacionesError" : "Observaciones invalido", 
        "_guardar" : "Salvar y Seguir",
        "_cancelar" : "Cancelar",
        "_titulo" : "Facturas.AMIBOGCXC"
    }