export const  AMIBOGCXC_Clientes_ES = {
        "ClienteAMIBOGCXCId" : "Id",
        "ClienteAMIBOGCXCIdError" : "Id invalido", 
        "ClienteAMIBOGCXCTipoId" : "Tipo Id",
        "_ClienteAMIBOGCXCTipoId" : {
            "Cedula_Ciduadania" : "Cedula Ciduadania",
            "Cedula_Extranjeria" : "Cedula Extranjeria",
            "Pasaporte" : "Pasaporte",
            "N.I.T" : "N.I.T",
            "R.U.T" : "R.U.T",
        },
        "ClienteAMIBOGCXCTipoIdError" : "Tipo Id invalido", 
        "ClienteAMIBOGCXCIdTributario" : "Id Tributario",
        "ClienteAMIBOGCXCIdTributarioError" : "Id Tributario invalido", 
        "ClienteAMIBOGCXCRazonSocial" : "Razon Social",
        "ClienteAMIBOGCXCRazonSocialError" : "Razon Social invalido", 
        "ClienteAMIBOGCXCPrimerApellido" : "Primer Apellido",
        "ClienteAMIBOGCXCPrimerApellidoError" : "Primer Apellido invalido", 
        "ClienteAMIBOGCXCSegundoApellido" : "Segundo Apellido",
        "ClienteAMIBOGCXCSegundoApellidoError" : "Segundo Apellido invalido", 
        "ClienteAMIBOGCXCPrimerNombre" : "Primer Nombre",
        "ClienteAMIBOGCXCPrimerNombreError" : "Primer Nombre invalido", 
        "ClienteAMIBOGCXCSegundoNombre" : "Segundo Nombre",
        "ClienteAMIBOGCXCSegundoNombreError" : "Segundo Nombre invalido", 
        "ClienteAMIBOGCXCDireccion" : "Direccion",
        "ClienteAMIBOGCXCDireccionError" : "Direccion invalido", 
        "CiudadDepartamentoId" : "Ciudad",
        "CiudadDepartamentoIdError" : "Ciudad invalido", 
        "Ciudadid" : "Ciudad",
        "CiudadidError" : "Ciudad invalido", 
        "CiudadNombreCiudad" : "Ciudad",
        "CiudadNombreCiudadError" : "Ciudad invalido", 
        "CodigoCiiuId" : "Codigo Ciiu",
        "CodigoCiiuIdError" : "Codigo Ciiu invalido", 
        "CodigoCiiuDescripcion" : "Codigo Ciiu",
        "CodigoCiiuDescripcionError" : "Codigo Ciiu invalido", 
        "ClienteAMIBOGCXCContactoCompras" : "Contacto Compras",
        "ClienteAMIBOGCXCContactoComprasError" : "Contacto Compras invalido", 
        "ClienteAMIBOGCXCCorreoCompras" : "Correo Compras",
        "ClienteAMIBOGCXCCorreoComprasError" : "Correo Compras invalido", 
        "ClienteAMIBOGCXCContactoTesoreria" : "Contacto Tesoreria",
        "ClienteAMIBOGCXCContactoTesoreriaError" : "Contacto Tesoreria invalido", 
        "ClienteAMIBOGCXCCorreoTesoreria" : "Correo Tesoreria",
        "ClienteAMIBOGCXCCorreoTesoreriaError" : "Correo Tesoreria invalido", 
        "ClienteAMIBOGCXCTelefono" : "Telefono",
        "ClienteAMIBOGCXCTelefonoError" : "Telefono invalido", 
        "ClienteAMIBOGCXCCelular" : "Celular",
        "ClienteAMIBOGCXCCelularError" : "Celular invalido", 
        "ClienteAMIBOGCXCDescuento" : "Descuento",
        "ClienteAMIBOGCXCDescuentoError" : "Descuento invalido", 
        "_guardar" : "Salvar y Seguir",
        "_cancelar" : "Cancelar",
        "_titulo" : "Clientes.AMIBOGCXC"
    }